/**
 * RPA Script Browser Agent — Background Service Worker
 *
 * Architecture:
 *   Backend (FastAPI WS)  <--WebSocket-->  background.js  <--chrome.tabs.sendMessage-->  content.js  <--DOM-->  Page
 *   Side Panel  <--chrome.runtime.onMessage-->  background.js  <--chrome.tabs.sendMessage-->  content_capture.js
 */

const DEFAULT_BACKEND_HOST = 'localhost';
const DEFAULT_BACKEND_PORT = 8811;
// 后端随机端口范围（与后端 _pick_free_port 保持一致）：8100-8199
const PORT_DISCOVER_LO = 8100;
const PORT_DISCOVER_HI = 8199;
const PORT_DISCOVER_CHUNK = 25;

function buildWsUrl(host, port) {
  return `ws://${host}:${port}/api/extension/ws`;
}

async function probeBackendHealth(host, port, timeoutMs = 600) {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), timeoutMs);
    const r = await fetch(`http://${host}:${port}/health`, { signal: ctrl.signal, cache: 'no-store' });
    clearTimeout(t);
    return r.ok;
  } catch (e) {
    return false;
  }
}

/**
 * 自动发现后端端口：先试 storage 缓存的端口；不通则在 8100-8199 范围
 * 分块并发探测 /health，命中后写回 storage（后端随机端口自适配）。
 * @returns {Promise<number|null>}
 */
async function discoverBackendPort(host, preferred) {
  const candidates = [];
  if (preferred && preferred >= 1024) candidates.push(preferred);
  for (let p = PORT_DISCOVER_LO; p <= PORT_DISCOVER_HI; p++) candidates.push(p);
  for (let i = 0; i < candidates.length; i += PORT_DISCOVER_CHUNK) {
    const chunk = candidates.slice(i, i + PORT_DISCOVER_CHUNK);
    const results = await Promise.all(chunk.map(p => probeBackendHealth(host, p).then(ok => (ok ? p : 0))));
    const found = results.find(p => p > 0);
    if (found) {
      try {
        await chrome.storage.local.set({ backendHost: host, backendPort: String(found) });
      } catch (e) {}
      console.log('[Agent] backend discovered on port', found);
      return found;
    }
  }
  return null;
}

/** 连接地址：缓存端口优先（立即连），失败自动发现新端口。 */
async function getBackendUrlWithDiscovery() {
  const cfg = await chrome.storage.local.get(['backendHost', 'backendPort']);
  const host = cfg.backendHost || DEFAULT_BACKEND_HOST;
  const preferred = parseInt(cfg.backendPort || '0', 10);
  if (preferred && (await probeBackendHealth(host, preferred, 400))) {
    return buildWsUrl(host, preferred);
  }
  const port = await discoverBackendPort(host, preferred);
  if (port) return buildWsUrl(host, port);
  return buildWsUrl(host, preferred || DEFAULT_BACKEND_PORT);
}

async function getBackendUrl() {
  const cfg = await chrome.storage.local.get(['backendHost', 'backendPort']);
  const host = cfg.backendHost || DEFAULT_BACKEND_HOST;
  const port = parseInt(cfg.backendPort || DEFAULT_BACKEND_PORT, 10);
  return buildWsUrl(host, port);
}

async function getBackendHost() {
  const cfg = await chrome.storage.local.get(['backendHost']);
  return cfg.backendHost || DEFAULT_BACKEND_HOST;
}

async function getBackendPort() {
  const cfg = await chrome.storage.local.get(['backendPort']);
  return parseInt(cfg.backendPort || DEFAULT_BACKEND_PORT, 10);
}

/**
 * Ensure the target tab has our content scripts injected.
 * Manifest-declared content scripts only auto-inject on navigation; tabs that
 * were already open (or that navigated before the extension loaded) need an
 * explicit injection before we can send them messages.
 */
async function ensureContentScripts(tabId) {
  try {
    await chrome.scripting.executeScript({
      target: { tabId },
      files: ['content.js', 'finder.js', 'content_capture.js'],
    });
  } catch (e) {
    console.warn('[Agent] ensureContentScripts failed for tab', tabId, e.message);
    throw e;
  }
}

// ── Background handler registry ──────────────────────────────
// Each extension/background_handlers/*.js calls registerBackgroundHandler()
// to self-register. background.js dispatches by type, no hardcoded type names.

const _backgroundHandlers = {};

function registerBackgroundHandler(type, fn) {
  _backgroundHandlers[type] = fn;
}

/**
 * 按 URL 片段在窗口中查找标签页，找不到时带重试。
 *
 * 解决 navigate 之后 tab.url 在 chrome.tabs 中提交存在时序延迟、
 * 导致 switchTab/closeTab 偶发匹配失败的问题：查询一次可能正落在
 * 「URL 已跳转但 tabs API 尚未更新」的瞬间，重试几次即可等到提交完成。
 */
async function findTabByUrlPattern(windowId, pattern, attempts = 4) {
  const p = String(pattern || '').toLowerCase();
  for (let i = 0; i < attempts; i++) {
    const tabs = await chrome.tabs.query({ windowId });
    const tab = tabs.find(t => t.url && t.url.toLowerCase().includes(p));
    if (tab) return tab;
    if (i < attempts - 1) await new Promise(r => setTimeout(r, 250));
  }
  return null;
}

// ─── Background handlers (generated by build_background_js.py) ───

class AgentBackground {
  constructor() {
    this.ws = null;
    this.reconnectTimer = null;
    this.pingTimer = null;
    this.clientId = null;
    this.pendingSteps = new Map(); // stepId -> {resolve, reject, timer}
    this.workTabId = null;
      this._lastTabUrl = null;         this._lastTabUrl = null;   // 工作流专用标签页 ID
    this.workWindowId = null;      // 工作流专用窗口 ID
    this.lastCapturePayload = null; // 最近一次捕获的元素数据（供 side panel 获取）
    this.lastCaptureTabId = null;   // 捕获来源标签页
    this.isRunning = false;         // 工作流运行中标志
    this.sidePanelOpen = false;     // side panel 是否打开
    this.guiCapture = null;         // GUI 网页捕获会话 { requestId, tabId, prevTabId, webOnly }
  }

  async start() {
    // 恢复工作窗口状态：MV3 service worker 会在空闲后休眠/重启，内存中的
    // workWindowId/workTabId 会丢失，导致步骤间"工作窗口已失效"。持久化到
    // chrome.storage.local，重启后在此恢复。
    try {
      const saved = await chrome.storage.local.get('rpaWorkState');
      const s = saved.rpaWorkState;
      if (s && s.workWindowId) {
        this.workWindowId = s.workWindowId;
        this.workTabId = s.workTabId || null;
        console.log('[Agent] restored work state:', this.workWindowId, this.workTabId);
      }
    } catch (_) {}

    const wsUrl = await getBackendUrlWithDiscovery();
    this._connect(wsUrl);

    // 点击扩展图标自动打开原生 Side Panel
    try {
      await chrome.sidePanel.setPanelBehavior({ openPanelOnActionClick: true });
    } catch (e) {
      console.warn('[Agent] sidePanel behavior not supported:', e.message);
    }

    // MV3 Service Worker keep-alive: 周期性闹钟防止浏览器暂停 Service Worker
    try {
      await chrome.alarms.create('keepAlive', { periodInMinutes: 0.5 });
    } catch (e) {
      console.warn('[Agent] alarms not supported:', e.message);
    }
  }

  _connect(wsUrl) {
    // 如果已有连接且目标 URL 相同，跳过
    if (this.ws?.url === wsUrl && (this.ws?.readyState === WebSocket.OPEN || this.ws?.readyState === WebSocket.CONNECTING)) {
      return;
    }

    // 如果已有连接但目标不同，强制关闭旧连接（切换后端端口）
    if (this.ws) {
      console.log('[Agent] Switching backend from', this.ws.url, 'to', wsUrl);
      try { this.ws.close(); } catch (e) {}
      this.ws = null;
    }

    // 清除旧的重连定时器，防止多个定时器同时触发
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }

    console.log('[Agent] Connecting to', wsUrl);
    this.ws = new WebSocket(wsUrl);

    this.ws.onopen = () => {
      console.log('[Agent] WS connected');
      const manifest = chrome.runtime.getManifest();
      this._send('register', {
        browser: this._detectBrowser(),
        version: manifest.version,
        extensionId: chrome.runtime.id || '',
        installType: 'development',
      });
      this._startPing();
    };

    this.ws.onmessage = (event) => {
      try {
        const msg = JSON.parse(event.data);
        this._onBackendMessage(msg);
      } catch (e) {
        console.error('[Agent] Invalid JSON from backend:', e);
      }
    };

    this.ws.onclose = () => {
      console.log('[Agent] WS closed, reconnecting with port discovery in 3s...');
      this._stopPing();
      this.reconnectTimer = setTimeout(async () => {
        const url = await getBackendUrlWithDiscovery();
        this._connect(url);
      }, 3000);
    };

    this.ws.onerror = (err) => {
      console.error('[Agent] WS error:', err);
    };
  }

  _detectBrowser() {
    const ua = navigator.userAgent;
    if (ua.includes('Edg/')) return 'edge';
    if (ua.includes('Chrome/')) return 'chrome';
    return 'unknown';
  }

  _send(action, payload = {}) {
    if (this.ws?.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify({ action, payload }));
    }
  }

  _startPing() {
    this.pingTimer = setInterval(() => {
      this._send('ping');
    }, 15000);
  }

  _stopPing() {
    if (this.pingTimer) {
      clearInterval(this.pingTimer);
      this.pingTimer = null;
    }
  }

  /**
   * Handle messages from backend.
   * Expected actions:
   *   - executeStep: { stepId, type, locator, selectorFamily, action, extra }
   */
  async _onBackendMessage(msg) {
    const { action, payload } = msg;
    console.log('[Agent] onBackendMessage:', action, JSON.stringify(payload).slice(0, 100));

    if (action === 'pong') return;

    if (action === 'executeStep') {
      await this._handleExecuteStep(payload);
      return;
    }

    if (action === 'runStarted') {
      this.isRunning = true;
      // Reset work window/tab references so navigate opens a fresh tab/window.
      // Do NOT close the actual browser window — if it's the only window,
      // removing it kills the browser process and breaks the extension connection.
      this.workWindowId = null;
      this.workTabId = null;
      this._lastTabUrl = null;
      await this._clearWorkState();
      console.log('[Agent] work window/tab reset for new run');
      return;
    }

    // GUI → Extension: 激活原生捕获模式
    if (action === 'launchBrowserCapture') {
      const { requestId } = payload || {};
      try {
        const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
        const tab = tabs[0];
        if (!tab) {
          this.guiCapture = null;
          this._send('browserCaptureComplete', { requestId, result: { error: '没有活动标签页' } });
          return;
        }
        // 记录 GUI 捕获会话（用于标签页切换时跟随重瞄）
        this.guiCapture = { requestId, tabId: tab.id, prevTabId: null, webOnly: !!payload?.webOnly, captureActive: false };
        await ensureContentScripts(tab.id);
        await new Promise(r => setTimeout(r, 300));  // 等脚本初始化
        // 重试 3 次
        for (let i = 0; i < 3; i++) {
          try {
            await chrome.tabs.sendMessage(tab.id, {
              action: 'launchBrowserCapture',
              payload: { requestId, webOnly: !!payload?.webOnly },
            });
            this.guiCapture.captureActive = true;
            break;  // 成功
          } catch (e) {
            if (i === 2) throw e;
            await new Promise(r => setTimeout(r, 300));
          }
        }
        // 等待 content script 通过 WS 发送结果
        // content_capture.js 会在捕获完成后通过 chrome.runtime.sendMessage
        // 发送 browserCaptureComplete 回来
      } catch (e) {
        // 启动页为受限页面（edge:// 等）或载入中：不结束会话，
        // 等用户切到普通网页（tabs.onActivated）或载入完成（tabs.onUpdated）后自动进入
        if (this.guiCapture) this.guiCapture.captureActive = false;
        this._send('browserCaptureNote', { requestId, note: '当前页面无法捕获（受限页面），请切换到普通网页' });
      }
      return;
    }

    // GUI → Extension: 退出浏览器捕获模式（超时/失败/取消时）
    if (action === 'exitBrowserCapture') {
      const gc = this.guiCapture;
      this.guiCapture = null;
      const targetIds = new Set();
      if (gc?.tabId != null) targetIds.add(gc.tabId);
      if (gc?.prevTabId != null) targetIds.add(gc.prevTabId);
      try {
        const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tabs[0]?.id != null) targetIds.add(tabs[0].id);
      } catch (e) {}
      // 向跟踪的捕获标签页（而非仅当前激活页）发退出，避免受限页/跨窗口时框选残留
      targetIds.forEach((tid) => chrome.tabs.sendMessage(tid, { action: 'exitCaptureMode' }).catch(() => {}));
      this._send('browserCaptureComplete', { requestId: payload?.requestId || '', result: { error: '已取消' } });
      return;
    }

    // GUI → Extension: 验证选择器 (只查物理可见页面: 非最小化窗口的 active tab)
    if (action === 'verifySelector') {
      const { requestId, selector } = payload || {};
      try {
        const wins = await chrome.windows.getAll({ populate: true });
        // 1. 过滤物理可见窗口（最小化 = 内容不在屏幕上）
        const visibleWins = wins.filter(w => w.state !== 'minimized');
        const focused = wins.find(w => w.focused) || null;
        // 2. 取每个可见窗口的 active tab（同窗口内只有 active tab 在屏幕上展示）
        let candidates = [];
        for (const w of visibleWins) {
          let tabs = [];
          try { tabs = await chrome.tabs.query({ windowId: w.id, active: true }); } catch (_) { continue; }
          const tab = tabs[0];
          if (!tab || tab.id == null || tab.discarded) continue;  // discarded = 内容已卸载，跳过
          candidates.push(tab);
        }
        // 3. 过滤编辑器/扩展/chrome 内部页（编辑器 SPA 按路径识别，端口已随机）
        candidates = candidates.filter(t =>
          t.url && /^https?:/i.test(t.url) &&
          !/workflow-editor\//i.test(t.url) &&
          !/chrome-extension:|chrome:|edge:|devtools:/i.test(t.url)
        );
        if (!candidates.length) {
          this._send('verifySelectorResult', { requestId, result: { found: false, count: 0, visible: 0, invisible: 0, error: '没有可见的网页标签页(请打开并展示目标页面)' } });
          return;
        }
        // 4. 排序: focused 窗口优先, 其余按 lastAccessed 降序（最近看的优先）
        candidates.sort((a, b) => {
          const af = focused && a.windowId === focused.id ? 0 : 1;
          const bf = focused && b.windowId === focused.id ? 0 : 1;
          if (af !== bf) return af - bf;
          return (b.lastAccessed || 0) - (a.lastAccessed || 0);
        });
        // 5. 逐个验证, 首个可见命中即返回
        const scanned = [];
        for (const tab of candidates) {
          let resp = null;
          try {
            await ensureContentScripts(tab.id);
            resp = await chrome.tabs.sendMessage(tab.id, {
              action: 'verifySelector',
              payload: { requestId, selector },
            });
          } catch (e) {
            resp = null;  // 注入/页面异常, 跳过继续
          }
          if (resp && resp.visible > 0) {
            // 提示: 打开多个相同页面时, 仅验证命中匹配到的这一个
            const sameUrlCount = candidates.filter(t => t.url === tab.url).length;
            this._send('verifySelectorResult', {
              requestId,
              result: {
                found: true, count: resp.count || 0, visible: resp.visible || 0, invisible: resp.invisible || 0,
                tabUrl: tab.url, tabTitle: tab.title || '',
                sameUrlCount,
              },
            });
            return;
          }
          scanned.push({
            tabUrl: tab.url, tabTitle: tab.title || '',
            count: resp?.count || 0, visible: resp?.visible || 0, invisible: resp?.invisible || 0,
          });
        }
        this._send('verifySelectorResult', {
          requestId,
          result: { found: false, count: 0, visible: 0, invisible: 0, scanned },
        });
      } catch (e) {
        this._send('verifySelectorResult', { requestId, result: { error: e?.message || String(e) } });
      }
      return;
    }

    // GUI → Extension: 拾取浏览器 DOM 元素
    if (action === 'browserPickElement') {
      const { x, y, requestId } = payload || {};
      try {
        const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
        const tab = tabs[0];
        if (!tab) {
          this._send('browserPickResult', { requestId, result: { error: '没有活动标签页' } });
          return;
        }
        const resp = await chrome.tabs.sendMessage(tab.id, {
          action: 'browserPickElement',
          payload: { x, y, requestId },
        });
        this._send('browserPickResult', { requestId, result: resp?.result || resp || { error: '无响应' } });
      } catch (e) {
        this._send('browserPickResult', { requestId, result: { error: e?.message || String(e) } });
      }
      return;
    }

    console.log('[Agent] Unknown backend action:', action);
  }

  _isRestrictedUrl(url) {
    if (!url) return true;
    // newtab / blank are safe automation targets (browser default start pages)
    if (url === 'about:blank' || url.includes('newtab')) return false;
    const restricted = ['chrome://', 'edge://', 'chrome-extension://', 'about:', 'file://', 'data:', 'javascript:'];
    return restricted.some(p => url.startsWith(p));
  }

  // ── 工作窗口状态持久化（MV3 service worker 休眠不丢） ──
  async _persistWorkState() {
    try {
      await chrome.storage.local.set({
        rpaWorkState: { workWindowId: this.workWindowId, workTabId: this.workTabId },
      });
    } catch (_) {}
  }

  async _clearWorkState() {
    try { await chrome.storage.local.remove('rpaWorkState'); } catch (_) {}
  }

  async _ensureWorkTab(step) {
    const explicitWindowId = step.extra?.windowId ? Number(step.extra.windowId) : null;
    const explicitTabId = step.extra?.tabId ? Number(step.extra.tabId) : null;

    if (explicitTabId) {
      try {
        const tab = await chrome.tabs.get(explicitTabId);
        if (tab && !this._isRestrictedUrl(tab.url)) {
          return explicitTabId;
        }
      } catch (e) {
        throw new Error('指定的标签页已失效');
      }
    }

    if (explicitWindowId) {
      try {
        const win = await chrome.windows.get(explicitWindowId, { populate: true });
        if (win && win.tabs) {
          const usable = win.tabs.find(t => !this._isRestrictedUrl(t.url));
          if (usable) return usable.id;
        }
      } catch (e) {}
      throw new Error('指定的窗口中没有可用标签页');
    }

    if (this.workWindowId) {
      try {
        const win = await chrome.windows.get(this.workWindowId);
        if (!win) {
          throw new Error('工作窗口已被关闭，请先执行打开浏览器指令');
        }
        if (this.workTabId) {
          try {
            const tab = await chrome.tabs.get(this.workTabId);
            if (tab && !this._isRestrictedUrl(tab.url)) {
              return this.workTabId;
            }
          } catch (e) {
            throw new Error('工作标签页已被手动关闭，请先执行打开浏览器指令');
          }
        }
        throw new Error('工作标签页已失效，请先执行打开浏览器指令');
      } catch (e) {
        if (e.message.includes('工作') || e.message.includes('指定')) throw e;
        throw new Error('工作窗口已失效，请先执行打开浏览器指令');
      }
    }

    throw new Error('未找到工作窗口，请先执行打开浏览器或导航步骤');
  }

  async _injectContentScript(tabId) {
    try {
      await chrome.scripting.executeScript({
        target: { tabId },
        files: ['content.js'],
      });
      console.log('[Agent] content.js injected into tab', tabId);
    } catch (e) {
      console.warn('[Agent] content.js injection failed:', e.message);
      throw e;
    }
  }

  async _executeStepOnTab(tabId, step) {
    // sendMessage 在 content script 存在但不回调 sendResponse 时永不 settle（既不 resolve 也不 reject），
    // 会导致后端 exec 永久挂起。加超时保护，超时明确报错而非挂死。
    const timeoutMs = 15000;
    let timer;
    const timeout = new Promise((_, reject) => {
      timer = setTimeout(() => reject(new Error(
        `目标标签页 content script 无响应（${timeoutMs / 1000}s），请刷新该页面或重载扩展后重试`
      )), timeoutMs);
    });
    try {
      return await Promise.race([
        chrome.tabs.sendMessage(tabId, { action: 'executeStep', step }),
        timeout,
      ]);
    } finally {
      clearTimeout(timer);
    }
  }

  async _handleExecuteStep(step) {
    const { stepId, type } = step;

    // ── Background handler dispatch (new system) ──
    const bgHandler = _backgroundHandlers[type];
    console.log('[Agent] _handleExecuteStep type=' + type + ' handlers=' + JSON.stringify(Object.keys(_backgroundHandlers)));
    if (bgHandler) {
      console.log('[Agent] dispatching to bg handler: ' + type);
      try {
        const result = await bgHandler(step, this);
        this._send('stepResult', { stepId, result });
      } catch (e) {
        this._send('stepError', { stepId, error: e.message });
      }
      return;
    }

    try {
      // Ensure we have a valid work tab (creates new one for navigate if needed)
      const tabId = await this._ensureWorkTab(step);

      // 操作前把目标窗口置前（best-effort）：真实鼠标/键盘操作必须窗口在前台才有效，
      // 也避免与用户当前所在窗口冲突。
      try {
        const workTab = await chrome.tabs.get(tabId);
        if (workTab?.windowId) {
          await chrome.windows.update(workTab.windowId, { focused: true });
        }
      } catch (_) {}

      // 向页面注入运行提示
      if (tabId) {
        chrome.tabs.sendMessage(tabId, { action: 'setRunningBanner', visible: true, stepType: type })
          .catch(() => {});
      }

      // Detect navigation caused by previous step BEFORE executing this one
      try {
        const prevTab = await chrome.tabs.get(tabId);
        if (this._lastTabUrl && prevTab.url !== this._lastTabUrl) {
          console.log('[Agent] tab navigated: ' + this._lastTabUrl + ' -> ' + prevTab.url);
          if (prevTab.status !== 'complete') {
            await new Promise((resolve) => {
              const listener = (tid, info) => {
                if (tid === tabId && info.status === 'complete') {
                  chrome.tabs.onUpdated.removeListener(listener);
                  resolve();
                }
              };
              chrome.tabs.onUpdated.addListener(listener);
              setTimeout(() => { chrome.tabs.onUpdated.removeListener(listener); resolve(); }, 5000);
            });
          }
          await this._injectContentScript(tabId);
          await new Promise(r => setTimeout(r, 500));
        }
        this._lastTabUrl = prevTab.url;
      } catch (_) {}

      // Try sending directly; if content script is missing, inject and retry once
      let result;
      try {
        result = await this._executeStepOnTab(tabId, step);
      } catch (sendErr) {
        const msg = sendErr?.message || '';
        const isMissing = msg.includes('Receiving end does not exist') || msg.includes('Could not establish connection');
        const isClosed = msg.includes('message channel') || msg.includes('back/forward cache');
        if (isMissing || isClosed) {
          console.log('[Agent] content script missing/closed (bfcache?), re-injecting...');
          await this._injectContentScript(tabId);
          await new Promise(r => setTimeout(r, 1500));
          result = await this._executeStepOnTab(tabId, step);
        } else {
          throw sendErr;
        }
      }

      if (result?.status === 'success') {
        // Enrich with screen coordinates if not already calibrated
        if (result?.result?.viewX !== undefined && result?.result?.screenX === undefined) {
          try {
            const tab = await chrome.tabs.get(tabId);
            if (tab) {
              const win = await chrome.windows.get(tab.windowId);
              const dpr = result.result.dpr || 1;
              const leftChrome = Math.round((win.width - tab.width) / 2);
              const topChrome = win.height - tab.height;
              const screenX = Math.round((win.left + leftChrome + result.result.viewX) * dpr);
              const screenY = Math.round((win.top + topChrome + result.result.viewY) * dpr);
              result.result.screenX = screenX;
              result.result.screenY = screenY;
            }
          } catch (_) {}
        }
        this._send('stepResult', { stepId, result: result.result });
      } else {
        this._send('stepError', { stepId, error: result?.error || 'Unknown content error' });
      }
    } catch (err) {
      console.error('[Agent] executeStep failed:', err);
      this._send('stepError', { stepId, error: err.message });
    }
  }
}

// Start agent
const agent = new AgentBackground();
agent.start();

// ── Extension command shortcuts (Alt+1 capture, Alt+2 verify) ──
chrome.commands.onCommand.addListener(async (command) => {
  if (!agent.sidePanelOpen) return;
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (!tab?.id) return;
  if (command === 'capture-element') {
    chrome.tabs.sendMessage(tab.id, { action: 'triggerCapture' }).catch(() => {});
  } else if (command === 'verify-element') {
    chrome.tabs.sendMessage(tab.id, { action: 'triggerVerify' }).catch(() => {});
  }
});

// ── GUI 网页捕获跟随标签页切换：切标签/切窗口时把捕获模式重瞄到新的激活标签页 ──
chrome.tabs.onActivated.addListener(({ tabId }) => {
  const gc = agent.guiCapture;
  if (!gc || tabId === gc.tabId) return;
  const prevTabId = gc.tabId;
  gc.tabId = tabId;
  gc.prevTabId = prevTabId;
  gc.captureActive = false;
  // 退出旧标签页捕获模式（保留会话，不结束）
  chrome.tabs.sendMessage(prevTabId, { action: 'exitCaptureMode' }).catch(() => {});
  // 进入新标签页捕获模式（尽力而为；注入失败不结束会话，等下一次切换/载入完成）
  const enter = () => chrome.tabs.sendMessage(tabId, {
    action: 'launchBrowserCapture',
    payload: { requestId: gc.requestId, webOnly: gc.webOnly },
  });
  enter().then(() => { gc.captureActive = true; }).catch(async () => {
    try {
      await ensureContentScripts(tabId);
      await enter();
      gc.captureActive = true;
    } catch (e) {
      gc.captureActive = false;
      console.warn('[RPA] GUI 捕获重瞄失败 tab=', tabId, e);
    }
  });
});

// ── GUI 网页捕获：同标签页载入完成后自动进入捕获（载入中启动/切换到的场景） ──
chrome.tabs.onUpdated.addListener((tabId, changeInfo) => {
  if (changeInfo.status !== 'complete') return;
  const gc = agent.guiCapture;
  if (!gc || tabId !== gc.tabId || gc.captureActive) return;
  gc.captureActive = true;  // 防重入
  const enter = () => chrome.tabs.sendMessage(tabId, {
    action: 'launchBrowserCapture',
    payload: { requestId: gc.requestId, webOnly: gc.webOnly },
  });
  enter().catch(async () => {
    gc.captureActive = false;  // 失败允许后续重试
    try {
      await ensureContentScripts(tabId);
      await enter();
      gc.captureActive = true;
    } catch (e) {
      gc.captureActive = false;
      console.warn('[RPA] onUpdated 重试失败 tab=', tabId, e);
    }
  });
});

// ── Handle messages from content scripts and side panel ──

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  // 0a) Content script 请求把当前标签页所在窗口置前台（输入前窗口前置）
  if (message.action === 'activateWindow') {
    const tab = sender.tab;
    if (!tab || tab.id == null) {
      sendResponse({ ok: false });
      return false;
    }
    (async () => {
      try {
        await chrome.tabs.update(tab.id, { active: true });
        await chrome.windows.update(tab.windowId, { focused: true });
        sendResponse({ ok: true });
      } catch (e) {
        sendResponse({ ok: false, error: e?.message || String(e) });
      }
    })();
    return true; // async
  }

  // 0) 选项页面请求立即重连（自动发现端口）
  if (message.action === 'reconnect') {
    (async () => {
      try {
        const host = message.host || DEFAULT_BACKEND_HOST;
        const port = message.port ? parseInt(message.port, 10) : 0;
        await chrome.storage.local.set({ backendHost: host });
        const wsUrl = port
          ? buildWsUrl(host, port)
          : await getBackendUrlWithDiscovery();
        if (port) await chrome.storage.local.set({ backendPort: String(port) });
        agent._connect(wsUrl);
        await new Promise(r => setTimeout(r, 1000));
        sendResponse({ connected: agent.ws?.readyState === WebSocket.OPEN });
      } catch (e) {
        sendResponse({ connected: false, error: e.message });
      }
    })();
    return true;
  }

  // 1) Side panel 请求最近一次捕获的数据
  if (message.action === 'getCapturePayload') {
    sendResponse({
      payload: agent.lastCapturePayload,
      tabId: agent.lastCaptureTabId,
    });
    return false;
  }

  // 1a) Side panel 选中候选方案 → 转发给捕获来源标签页
  if (message.action === 'selectCandidate') {
    const tabId = agent.lastCaptureTabId;
    if (!tabId) {
      sendResponse({ forwarded: false, error: 'no capture tab' });
      return false;
    }
    chrome.tabs.sendMessage(tabId, { action: 'selectCandidate', payload: message.payload }).catch(() => {});
    sendResponse({ forwarded: true });
    return false;
  }

  // 2) Side panel 请求校验元素 → 转发给对应标签页的 content_capture.js
  if (message.action === 'verifyElement') {
    console.log('[Agent] verifyElement received:', JSON.stringify(message).slice(0, 200));
    // sidepanel.js 的 send() 把参数包在 payload 里: { action, payload: { tabId, payload } }
    const tabId = message.tabId ?? message.payload?.tabId;
    const payload = message.payload?.payload ?? message.payload;
    console.log('[Agent] verifyElement: tabId=' + tabId + ' payloadKeys=' + Object.keys(payload || {}).join(','));
    if (!tabId) {
      console.log('[Agent] verifyElement: missing tabId');
      sendResponse({ error: 'tabId required' });
      return false;
    }
    ensureContentScripts(tabId)
      .then(() => {
        console.log('[Agent] verifyElement: forwarding to tab ' + tabId);
        return chrome.tabs.get(tabId).then(tab => {
          console.log('[Agent] verifyElement: tab URL = ' + (tab?.url || 'unknown'));
          return chrome.tabs.sendMessage(tabId, { action: 'verifyElement', payload });
        });
      })
      .then(result => {
        console.log('[Agent] verifyElement: tab responded', result);
        sendResponse(result);
      })
      .catch(err => {
        console.log('[Agent] verifyElement: error ' + err.message);
        sendResponse({ error: err.message });
      });
    return true; // async
  }

  // 2a) Side panel 请求重新计算循环锚点 → 转发给捕获标签页
  if (message.action === 'recomputeAnchor') {
    const tabId = message.tabId ?? message.payload?.tabId;
    const payload = message.payload?.payload ?? message.payload;
    if (!tabId) {
      sendResponse({ error: 'tabId required' });
      return false;
    }
    ensureContentScripts(tabId)
      .then(() => chrome.tabs.sendMessage(tabId, { action: 'recomputeAnchor', payload }))
      .then(result => sendResponse(result))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  // 2b) Side panel 请求校验相对选择器 → 转发给捕获标签页
  if (message.action === 'verifyRelative') {
    const tabId = message.tabId ?? message.payload?.tabId;
    const payload = message.payload?.payload ?? message.payload;
    if (!tabId) {
      sendResponse({ error: 'tabId required' });
      return false;
    }
    ensureContentScripts(tabId)
      .then(() => chrome.tabs.sendMessage(tabId, { action: 'verifyRelative', payload }))
      .then(result => sendResponse(result))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  // 2c) Side panel 请求根据已选锚点计算相对选择器 → 转发给捕获标签页
  if (message.action === 'computeRelativeFromAnchor') {
    const tabId = message.tabId ?? message.payload?.tabId;
    const payload = message.payload?.payload ?? message.payload;
    if (!tabId) {
      sendResponse({ error: 'tabId required' });
      return false;
    }
    ensureContentScripts(tabId)
      .then(() => chrome.tabs.sendMessage(tabId, { action: 'computeRelativeFromAnchor', payload }))
      .then(result => sendResponse(result))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  // 2d) Side panel 设置/清除“当前激活锚点”（锚点优先捕获）→ 转发给可见标签页
  if (message.action === 'setActiveAnchor') {
    const payload = message.payload?.payload ?? message.payload ?? {};
    const explicitTab = message.tabId ?? message.payload?.tabId;
    const forward = (tid) => {
      if (!tid) { sendResponse({ error: 'no active tab' }); return; }
      ensureContentScripts(tid)
        .then(() => chrome.tabs.sendMessage(tid, { action: 'setActiveAnchor', payload }))
        .then((result) => sendResponse(result))
        .catch((err) => sendResponse({ error: err.message }));
    };
    if (explicitTab) {
      forward(explicitTab);
    } else {
      chrome.tabs.query({ active: true, lastFocusedWindow: true })
        .then((tabs) => forward(tabs?.[0]?.id ?? agent.lastCaptureTabId))
        .catch(() => forward(agent.lastCaptureTabId));
    }
    return true;
  }

  // 3) Content script 返回校验结果 → 广播给 side panel
  if (message.action === 'verifyResult') {
    // Broadcast to side panel (and anyone listening)
    chrome.runtime.sendMessage({ action: 'verifyResultBroadcast', payload: message.payload })
      .catch(() => {});
    sendResponse({ forwarded: true });
    return false;
  }

  // 4) Content script 通知捕获完成 → 缓存数据并打开 side panel（不保存到后台）
  // content_capture.js → WS: GUI 原生捕获模式结果
  if (message.action === 'browserCaptureComplete') {
    agent.guiCapture = null;
    agent._send('browserCaptureComplete', message.payload);
    sendResponse({ ok: true });
    return false;
  }

  // 4a) Content script 通知 GUI 捕获取消（Esc）→ 转发 WS 让 overlay 退出
  if (message.action === 'browserCaptureCancelled') {
    agent.guiCapture = null;
    agent._send('browserCaptureComplete', {
      requestId: message.payload?.requestId,
      result: { error: '已取消', backToDesktop: !!message.payload?.backToDesktop },
    });
    sendResponse({ ok: true });
    return false;
  }

  // 4b) Content script 上报 GUI 捕获悬停元素信息 → 转发 WS，overlay 悬浮窗实时显示
  if (message.action === 'guiHoverInfo') {
    agent._send('guiHoverInfo', message.payload);
    sendResponse({ ok: true });
    return false;
  }

  if (message.action === 'captureElement') {
    agent.lastCapturePayload = message.payload;
    agent.lastCaptureTabId = sender.tab?.id || null;

    // Notify side panel to refresh (in case it's already open)
    chrome.runtime.sendMessage({ action: 'newCaptureAvailable' }).catch(() => {});

    // Open side panel on the capturing tab
    if (sender.tab?.id) {
      try {
        chrome.sidePanel.open({ tabId: sender.tab.id }).catch(() => {});
      } catch (_e) {}
    }
    sendResponse({ cached: true });
    return false;
  }

  // 5) Side panel 点击保存 → 转发到后端
  // 保存元素（通过 HTTP 同步等待后端结果）
  if (message.action === 'saveElement') {
    (async () => {
      try {
        const host = await getBackendHost();
        const port = await getBackendPort();
        const resp = await fetch(`http://${host}:${port}/api/extension/elements`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(message.payload),
        });
        const data = await resp.json();
        if (!resp.ok) {
          sendResponse({ saved: false, error: data?.detail || resp.statusText });
          return;
        }
        sendResponse({ saved: true, element: data });
      } catch (e) {
        sendResponse({ saved: false, error: e.message });
      }
    })();
    return true;
  }

  // 5a) Side panel 请求流程列表
  if (message.action === 'getWorkflows') {
    (async () => {
      try {
        const host = await getBackendHost();
        const port = await getBackendPort();
        const resp = await fetch(`http://${host}:${port}/api/extension/workflows`);
        const data = await resp.json();
        sendResponse({ workflows: data });
      } catch (e) {
        sendResponse({ error: e.message });
      }
    })();
    return true;
  }

  // 5b) Side panel 请求流程元素列表
  if (message.action === 'getWorkflowElements') {
    (async () => {
      try {
        const host = await getBackendHost();
        const port = await getBackendPort();
        const wfId = message.workflowId;
        const resp = await fetch(`http://${host}:${port}/api/extension/elements?workflow_id=${wfId}`);
        const data = await resp.json();
        sendResponse({ elements: data });
      } catch (e) {
        sendResponse({ error: e.message });
      }
    })();
    return true;
  }

  // 5c) Side panel 请求某个元素的有效选择器链（支持 child 作为锚点）
  if (message.action === 'getElementChain') {
    (async () => {
      try {
        const host = await getBackendHost();
        const port = await getBackendPort();
        const { workflowId, name } = message.payload || {};
        const resp = await fetch(`http://${host}:${port}/api/extension/elements/${encodeURIComponent(name)}/chain?workflow_id=${encodeURIComponent(workflowId)}`);
        const data = await resp.json();
        sendResponse(data);
      } catch (e) {
        sendResponse({ error: e.message });
      }
    })();
    return true;
  }

  // 5d) Side panel 请求单个元素完整数据（用于编辑现有元素）
  if (message.action === 'getElementByName') {
    (async () => {
      try {
        const host = await getBackendHost();
        const port = await getBackendPort();
        const { workflowId, name } = message.payload || {};
        console.log('[Background] getElementByName request:', { workflowId, name });
        const url = `http://${host}:${port}/api/extension/elements/${encodeURIComponent(name)}?workflow_id=${encodeURIComponent(workflowId)}`;
        const resp = await fetch(url);
        const data = await resp.json().catch(() => ({}));
        if (!resp.ok) {
          console.warn('[Background] getElementByName failed:', resp.status, url, data);
          sendResponse({ error: data?.detail || data?.error || `HTTP ${resp.status}` });
          return;
        }
        console.log('[Background] getElementByName response:', data);
        sendResponse(data);
      } catch (e) {
        console.warn('[Background] getElementByName error:', e);
        sendResponse({ error: e.message || String(e) });
      }
    })();
    return true;
  }

  // 6) Content script 查询当前捕获启用状态（页面刷新后同步）
  if (message.action === 'queryCaptureState') {
    sendResponse({ captureEnabled: agent.sidePanelOpen });
    return false;
  }

  if (message.action === 'captureScreenshot') {
    chrome.tabs.captureVisibleTab({ format: 'png' })
      .then(dataUrl => sendResponse({ dataUrl }))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  if (message.action === 'captureElementScreenshot') {
    const { rect, dpr = 1 } = message;
    const padding = 10 * dpr;

    chrome.tabs.captureVisibleTab({ format: 'png' })
      .then(async (dataUrl) => {
        try {
          const resp = await fetch(dataUrl);
          const blob = await resp.blob();
          const bitmap = await createImageBitmap(blob);

          const sx = Math.max(0, Math.round(rect.left * dpr - padding));
          const sy = Math.max(0, Math.round(rect.top * dpr - padding));
          const sw = Math.min(bitmap.width - sx, Math.round(rect.width * dpr + padding * 2));
          const sh = Math.min(bitmap.height - sy, Math.round(rect.height * dpr + padding * 2));

          const canvas = new OffscreenCanvas(sw, sh);
          const ctx = canvas.getContext('2d');
          ctx.drawImage(bitmap, sx, sy, sw, sh, 0, 0, sw, sh);

          const croppedBlob = await canvas.convertToBlob({ type: 'image/png' });
          const reader = new FileReader();
          reader.onloadend = () => sendResponse({ dataUrl: reader.result });
          reader.readAsDataURL(croppedBlob);
        } catch (err) {
          sendResponse({ error: err.message });
        }
      })
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  if (message.action === 'notifyElementCaptured') {
    chrome.tabs.query({}, (tabs) => {
      tabs.forEach((tab) => {
        if (!tab.id) return;
        chrome.tabs.sendMessage(tab.id, { action: 'elementCaptured', payload: message.payload })
          .catch(() => {});
      });
    });
    sendResponse({ broadcast: true });
    return false;
  }

  // 7) 查询 WebSocket 连接状态
  if (message.action === 'getConnectionStatus') {
    sendResponse({ connected: agent.ws?.readyState === WebSocket.OPEN });
    return false;
  }

  return false;
});

// ── Side Panel 长连接生命周期（比 beforeunload 可靠）──
chrome.runtime.onConnect.addListener((port) => {
  if (port.name !== 'sidePanel') return;

  // side panel 打开
  agent.sidePanelOpen = true;
  const enabled = true;
  chrome.tabs.query({}, (tabs) => {
    tabs.forEach((tab) => {
      if (!tab.id) return;
      chrome.tabs.sendMessage(tab.id, { action: 'setCaptureEnabled', enabled })
        .catch(() => {});
    });
  });

  port.onDisconnect.addListener(() => {
    // side panel 关闭
    agent.sidePanelOpen = false;
    const enabled = false;
    chrome.tabs.query({}, (tabs) => {
      tabs.forEach((tab) => {
        if (!tab.id) return;
        chrome.tabs.sendMessage(tab.id, { action: 'setCaptureEnabled', enabled })
          .catch(() => {});
      });
    });
  });
});

// MV3 keep-alive: 闹钟触发时检查并重连 WS，防止 Service Worker 被浏览器暂停后断连
chrome.alarms.onAlarm.addListener(async (alarm) => {
  if (alarm.name === 'keepAlive') {
    console.log('[Agent] keepAlive alarm');
    if (!agent.ws || agent.ws.readyState !== WebSocket.OPEN) {
      console.log('[Agent] reconnecting from keepAlive alarm');
      const wsUrl = await getBackendUrlWithDiscovery();
      agent._connect(wsUrl);
    } else {
      // WS 正常，发送 ping 保持连接活跃
      agent._send('ping');
    }
  }
});
