# AUTO-GENERATED by workflow exporter
# DO NOT EDIT — changes will be overwritten

import sys, os, random, time, json, re
_repo = os.environ.get('RPA_REPO_ROOT', 'C:\\Users\\liqt91\\Projects\\rpa-script')
_project_root = os.path.dirname(_repo)
if _project_root and _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from src.repo.chrome_utils import connect_chrome

_VAR_PLACEHOLDER_RE = re.compile(r'\$\{(\w+)\}|\{\{(\w+)\}\}')

def _resolve_vars(value):
    if isinstance(value, str):
        def _repl(m):
            key = m.group(1) or m.group(2)
            return str(globals().get(key, m.group(0)))
        return _VAR_PLACEHOLDER_RE.sub(_repl, value)
    return value

def _ensure_table_rows(table_data, row_idx):
    rows = table_data.setdefault('rows', [])
    while len(rows) <= row_idx:
        rows.append({})
    return rows

def _coerce_row_data(raw):
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except Exception:
            return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, list):
        cols = _table_data.get('columns', [])
        return {(cols[i]['name'] if i < len(cols) else chr(65 + i)): v for i, v in enumerate(raw)}
    return {}

def _human_delay(min_sec=0.3, max_sec=1.5):
    time.sleep(random.uniform(min_sec, max_sec))

def _ele_visible(tab, loc):
    eles = tab.eles(loc)
    for e in eles:
        try:
            if e.is_displayed():
                return e
        except Exception:
            pass
    return eles[0] if eles else None

def _ele_exists(tab, loc):
    try:
        return bool(tab.ele(loc))
    except Exception:
        return False

def _try_locators(tab, locs, method='ele', visible_only=False):
    for loc in locs:
        try:
            if method == 'ele':
                if visible_only:
                    eles = tab.eles(loc)
                    for e in eles:
                        try:
                            if e.is_displayed():
                                return e
                        except Exception:
                            pass
                    if eles:
                        return eles[0]
                else:
                    el = tab.ele(loc)
                    if el:
                        return el
            elif method == 'eles':
                els = tab.eles(loc)
                if els:
                    return els
            elif method == 's_ele':
                el = tab.s_ele(loc)
                if el:
                    return el
            elif method == 's_eles':
                els = tab.s_eles(loc)
                if els:
                    return els
        except Exception:
            continue
    if method in ('ele', 's_ele'):
        return None
    return []

# Workflow error handler — fallback for exceptions outside instruction wrappers
import traceback, re

def _wf_excepthook(exc_type, exc_value, tb):
    node_info = None
    t = tb
    while t:
        co = t.tb_frame.f_code
        if co.co_filename == __file__:
            lineno = t.tb_lineno
            try:
                with open(__file__, 'r', encoding='utf-8') as f:
                    src = f.readlines()
                for i in range(lineno - 1, -1, -1):
                    m = re.search(r'# WF_NODE id=(\d+) type=(\S+) label=(.+)', src[i])
                    if m:
                        node_info = {'id': int(m.group(1)), 'type': m.group(2), 'label': m.group(3).strip()}
                        break
            except Exception:
                pass
            if node_info:
                break
        t = tb.tb_next
    if node_info:
        label = node_info['label']
        print(f"[WF_ERROR] 指令 #{node_info['id']} ({node_info['type']}) {label}", file=sys.stderr)
    traceback.print_exception(exc_type, exc_value, tb)

sys.excepthook = _wf_excepthook

# Workflow parameters
url = ''

# Workflow: 小红书评论采集
# URL: TODO

tab = connect_chrome()
if not tab:
    raise RuntimeError('无法连接到 Chrome，请确保 Chrome 已启动并开启了远程调试端口 9222')

_results = []
_table_data = {'columns': [], 'rows': []}

# WF_NODE id=25 type=openBrowser label=打开浏览器
try:
    tab = page.new_tab({'browser': 'edge', 'url': 'about:blank', 'state': 'normal'})  # openBrowser
    _human_delay()
except Exception as _e:
    print(f"[WF_ERROR] 指令 #25 (openBrowser) 打开浏览器: {_e}", file=sys.stderr)
    raise
# WF_NODE id=26 type=navigate label=打开网页
try:
    tab.get('${url}')
    _human_delay()
except Exception as _e:
    print(f"[WF_ERROR] 指令 #26 (navigate) 打开网页: {_e}", file=sys.stderr)
    raise
# WF_NODE id=27 type=getText label=获取元素文本
try:
    帖子作者 = _ele_visible(tab, "xpath://span[contains(@class,'username')]").text
    _human_delay()
except Exception as _e:
    print(f"[WF_ERROR] 指令 #27 (getText) 获取元素文本: {_e}", file=sys.stderr)
    pass  # continue on error
# WF_NODE id=28 type=getText label=获取元素文本
try:
    发帖时间地点 = _ele_visible(tab, "xpath://span[contains(@class,'date')]").text
    _human_delay()
except Exception as _e:
    print(f"[WF_ERROR] 指令 #28 (getText) 获取元素文本: {_e}", file=sys.stderr)
    raise
# WF_NODE id=29 type=whileCondition label=循环直到条件成立
_iter = 0
while _iter < 1000:
    # WF_NODE id=30 type=whileCondition label=循环直到条件成立
    _iter = 0
    while _iter < 10:
        if not tab.ele("xpath://div[contains(@class,'show-more')]"):
            break
        # WF_NODE id=31 type=click label=点击元素
        try:
            _ele_visible(tab, "xpath://div[contains(@class,'show-more')]").click()
            _human_delay()
        except Exception as _e:
            print(f"[WF_ERROR] 指令 #31 (click) 点击元素: {_e}", file=sys.stderr)
            raise
        # WF_NODE id=32 type=randomSleep label=等待随机时间
        try:
            time.sleep(random.uniform(0.1, 0.3))
            _human_delay()
        except Exception as _e:
            print(f"[WF_ERROR] 指令 #32 (randomSleep) 等待随机时间: {_e}", file=sys.stderr)
            raise
        _iter += 1
    # WF_NODE id=33 type=endFor label=结束循环
    # WF_NODE id=34 type=scrollToBottom label=滚动到底部
    try:
        tab.scroll.to_bottom()
        _human_delay()
    except Exception as _e:
        print(f"[WF_ERROR] 指令 #34 (scrollToBottom) 滚动到底部: {_e}", file=sys.stderr)
        raise
    # WF_NODE id=35 type=randomSleep label=等待随机时间
    try:
        time.sleep(random.uniform(0.1, 1))
        _human_delay()
    except Exception as _e:
        print(f"[WF_ERROR] 指令 #35 (randomSleep) 等待随机时间: {_e}", file=sys.stderr)
        raise
    _iter += 1
    if tab.ele("xpath://div[contains(@class,'end-container')]"):
        break
# WF_NODE id=36 type=endFor label=结束循环
# WF_NODE id=37 type=whileCondition label=循环直到条件成立
_iter = 0
while _iter < 10:
    if not tab.ele("xpath://div[contains(@class,'show-more')]"):
        break
    # WF_NODE id=38 type=click label=点击元素
    try:
        _ele_visible(tab, "xpath://div[contains(@class,'show-more')]").click()
        _human_delay()
    except Exception as _e:
        print(f"[WF_ERROR] 指令 #38 (click) 点击元素: {_e}", file=sys.stderr)
        raise
    # WF_NODE id=39 type=randomSleep label=等待随机时间
    try:
        time.sleep(random.uniform(0.1, 0.3))
        _human_delay()
    except Exception as _e:
        print(f"[WF_ERROR] 指令 #39 (randomSleep) 等待随机时间: {_e}", file=sys.stderr)
        raise
    _iter += 1
# WF_NODE id=40 type=endFor label=结束循环
# WF_NODE id=41 type=forEachElement label=循环相似元素
for index, item in enumerate(tab):
    # WF_NODE id=42 type=getText label=获取元素文本
    try:
        主评论 = tab.text
        _human_delay()
    except Exception as _e:
        print(f"[WF_ERROR] 指令 #42 (getText) 获取元素文本: {_e}", file=sys.stderr)
        raise
    # WF_NODE id=43 type=writeTableRow label=写入表格行
    try:
        _row_raw = _resolve_vars('[${主评论}]')
        _row_data = _coerce_row_data(_row_raw)
        _table_data['rows'].append(_row_data)
        _human_delay()
    except Exception as _e:
        print(f"[WF_ERROR] 指令 #43 (writeTableRow) 写入表格行: {_e}", file=sys.stderr)
        raise
    # WF_NODE id=44 type=forEachElement label=循环相似元素
    for index, item in enumerate(tab):
        # WF_NODE id=45 type=getText label=获取元素文本
        try:
            子评论 = tab.text
            _human_delay()
        except Exception as _e:
            print(f"[WF_ERROR] 指令 #45 (getText) 获取元素文本: {_e}", file=sys.stderr)
            raise
        # WF_NODE id=46 type=writeTableRow label=写入表格行
        try:
            _row_raw = _resolve_vars('[${子评论}]')
            _row_data = _coerce_row_data(_row_raw)
            _table_data['rows'].append(_row_data)
            _human_delay()
        except Exception as _e:
            print(f"[WF_ERROR] 指令 #46 (writeTableRow) 写入表格行: {_e}", file=sys.stderr)
            raise
    # WF_NODE id=47 type=endFor label=结束循环
# WF_NODE id=48 type=endFor label=结束循环

print('Workflow completed')
print(f'Results: {len(_results)} items')