"""
Workflow → DrissionPage Python script exporter.

Each command type has its own emit_* function for clean separation.
"""

import json
from typing import Any

from src.repo import runtime_models as models


def build_python(wf: models.Workflow, flat_nodes: list[models.WorkflowNode], repo_root: str = "") -> list[str]:
    """Generate DrissionPage Python lines from a workflow and its nodes."""
    print(f"[exporter] building python for '{wf.name}' with {len(flat_nodes)} nodes")
    lines = [
        "# AUTO-GENERATED by workflow exporter",
        "# DO NOT EDIT — changes will be overwritten",
        "",
        "import sys, os",
        f"_repo = os.environ.get('RPA_REPO_ROOT', {repr(repo_root)})",
        "_project_root = os.path.dirname(_repo)",
        "if _project_root and _project_root not in sys.path:",
        "    sys.path.insert(0, _project_root)",
        "",
        "from src.repo.chrome_utils import connect_chrome",
        "",
        "# Workflow error handler — maps traceback back to workflow node",
        "import traceback, re",
        "",
        "def _wf_excepthook(exc_type, exc_value, tb):",
        "    node_info = None",
        "    t = tb",
        "    while t:",
        "        co = t.tb_frame.f_code",
        "        if co.co_filename == __file__:",
        "            lineno = t.tb_lineno",
        "            try:",
        "                with open(__file__, 'r', encoding='utf-8') as f:",
        "                    src = f.readlines()",
        "                for i in range(lineno - 1, -1, -1):",
        "                    m = re.search(r'# WF_NODE id=(\\d+) type=(\\S+) label=(.+)', src[i])",
        "                    if m:",
        "                        node_info = {'id': int(m.group(1)), 'type': m.group(2), 'label': m.group(3).strip()}",
        "                        break",
        "            except Exception:",
        "                pass",
        "            if node_info:",
        "                break",
        "        t = t.tb_next",
        "    if node_info:",
        "        print(f\"[WF_ERROR] 指令 #{node_info['id']} ({node_info['type']}) {node_info['label']}\", file=sys.stderr)",
        "    traceback.print_exception(exc_type, exc_value, tb)",
        "",
        "sys.excepthook = _wf_excepthook",
        "",
        f"# Workflow: {wf.name}",
        f"# URL: {wf.url or 'TODO'}",
        "",
        "tab = connect_chrome()",
        "if not tab:",
        "    raise RuntimeError('无法连接到 Chrome，请确保 Chrome 已启动并开启了远程调试端口 9222')",
    ]
    if wf.url:
        lines.append(f"tab.get('{wf.url}')")
    lines.append("")

    # Build parent→children map
    by_parent: dict[int | None, list[models.WorkflowNode]] = {}
    for n in flat_nodes:
        pid = n.parent_id
        by_parent.setdefault(pid, []).append(n)
    for children in by_parent.values():
        children.sort(key=lambda n: n.order)

    # Collect results container
    lines.append("_results = []")
    lines.append("")

    def _emit(node: models.WorkflowNode, depth: int = 0) -> None:
        extra = json.loads(node.extra) if node.extra else {}
        _emit_dispatch(node, extra, depth, by_parent, lines)

    # Emit root nodes
    for n in by_parent.get(None, []):
        _emit(n, 0)

    lines.append("")
    lines.append("print('Workflow completed')")
    lines.append(f"print(f'Results: {{len(_results)}} items')")
    return lines


def _indent(depth: int) -> str:
    return "    " * depth


def _loc_call(node: models.WorkflowNode, extra: dict) -> str:
    """Build tab.ele('...') style locator call."""
    loc = (node.locator or "").replace("'", "\\'")
    method = node.method or "ele"
    if not loc:
        return "tab"
    return f"tab.{method}('{loc}')"


def _var_ref(name: str) -> str:
    """Sanitize variable name."""
    return name.strip() if name else "_tmp"


def _emit_dispatch(node: models.WorkflowNode, extra: dict, depth: int,
                   by_parent: dict, lines: list[str]) -> None:
    prefix = _indent(depth)
    from src.runtime.workflow.commands import COMMAND_REGISTRY
    cmd = COMMAND_REGISTRY.get(node.type, {})
    label = cmd.get("label", node.type)
    lines.append(f"{prefix}# WF_NODE id={node.id} type={node.type} label={label}")
    handler = _EMIT_HANDLERS.get(node.type)

    if handler:
        handler(node, extra, depth, prefix, by_parent, lines)
    else:
        # Unknown type — emit a placeholder
        loc = _loc_call(node, extra)
        lines.append(f"{prefix}# TODO: {node.type} -> {loc}")


# ═══════════════════════════════════════════════════════════════════
# Emit handlers per command type
# ═══════════════════════════════════════════════════════════════════

_EMIT_HANDLERS: dict[str, Any] = {}


def _handler(name: str):
    def decorator(fn):
        _EMIT_HANDLERS[name] = fn
        return fn
    return decorator


# ── Navigation ────────────────────────────────────────────────────

@_handler("navigate")
def _emit_navigate(node, extra, depth, prefix, by_parent, lines):
    url = (extra.get("url") or "").replace("'", "\\'")
    wait = extra.get("waitLoad", True)
    timeout = extra.get("timeout", 30)
    if wait:
        lines.append(f"{prefix}tab.get('{url}')")
    else:
        lines.append(f"{prefix}tab.get('{url}', go_timeout={timeout})")


@_handler("goBack")
def _emit_goBack(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}tab.back()")


@_handler("goForward")
def _emit_goForward(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}tab.forward()")


@_handler("refresh")
def _emit_refresh(node, extra, depth, prefix, by_parent, lines):
    if extra.get("hardReload"):
        lines.append(f"{prefix}tab.refresh(ignore_cache=True)")
    else:
        lines.append(f"{prefix}tab.refresh()")


@_handler("newTab")
def _emit_newTab(node, extra, depth, prefix, by_parent, lines):
    url = extra.get("url", "").replace("'", "\\'")
    if url:
        lines.append(f"{prefix}tab.new_tab('{url}')")
    else:
        lines.append(f"{prefix}tab.new_tab()")


@_handler("closeTab")
def _emit_closeTab(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}tab.close_tabs(tab)")


@_handler("switchTab")
def _emit_switchTab(node, extra, depth, prefix, by_parent, lines):
    by = extra.get("by", "index")
    value = extra.get("value", "")
    if by == "index":
        lines.append(f"{prefix}tab.to_tab({value})")
    elif by == "url":
        lines.append(f"{prefix}tab.to_tab(url='{value}')")
    elif by == "title":
        lines.append(f"{prefix}tab.to_tab(title='{value}')")


@_handler("switchToFrame")
def _emit_switchToFrame(node, extra, depth, prefix, by_parent, lines):
    loc = (node.locator or "").replace("'", "\\'")
    lines.append(f"{prefix}tab.to_frame('{loc}')")


@_handler("switchToMain")
def _emit_switchToMain(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}tab.to_main()")


@_handler("getCurrentUrl")
def _emit_getCurrentUrl(node, extra, depth, prefix, by_parent, lines):
    var = _var_ref(extra.get("varName", "currentUrl"))
    lines.append(f"{prefix}{var} = tab.url")


@_handler("getPageTitle")
def _emit_getPageTitle(node, extra, depth, prefix, by_parent, lines):
    var = _var_ref(extra.get("varName", "pageTitle"))
    lines.append(f"{prefix}{var} = tab.title")


# ── Click ─────────────────────────────────────────────────────────

@_handler("click")
def _emit_click(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    if extra.get("forceJs"):
        lines.append(f"{prefix}{call}.click(by_js=True)")
    else:
        lines.append(f"{prefix}{call}.click()")


@_handler("doubleClick")
def _emit_doubleClick(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}{call}.click(times=2)")


@_handler("rightClick")
def _emit_rightClick(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}{call}.click(button='right')")


@_handler("clickByIndex")
def _emit_clickByIndex(node, extra, depth, prefix, by_parent, lines):
    loc = (node.locator or "").replace("'", "\\'")
    idx = extra.get("index", 0)
    lines.append(f"{prefix}tab.eles('{loc}')[{idx}].click()")


@_handler("clickIfExists")
def _emit_clickIfExists(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}_el = {call}")
    lines.append(f"{prefix}if _el:")
    lines.append(f"{prefix}    _el.click()")


@_handler("hover")
def _emit_hover(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}{call}.hover()")


# ── Input ─────────────────────────────────────────────────────────

@_handler("input")
def _emit_input(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    text = (extra.get("text") or "").replace("'", "\\'")
    if extra.get("clearFirst", True):
        lines.append(f"{prefix}{call}.clear()")
    lines.append(f"{prefix}{call}.input('{text}')")


@_handler("inputAndPressEnter")
def _emit_inputAndPressEnter(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    text = (extra.get("text") or "").replace("'", "\\'")
    if extra.get("clearFirst", True):
        lines.append(f"{prefix}{call}.clear()")
    lines.append(f"{prefix}{call}.input('{text}')")
    lines.append(f"{prefix}{call}.input(Keys.ENTER)")


@_handler("clearInput")
def _emit_clearInput(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}{call}.clear()")


@_handler("pressKey")
def _emit_pressKey(node, extra, depth, prefix, by_parent, lines):
    key = extra.get("key", "Enter")
    lines.append(f"{prefix}tab.actions.key_down(Keys.{key}).key_up(Keys.{key})")


@_handler("selectOption")
def _emit_selectOption(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    by = extra.get("by", "label")
    value = (extra.get("value") or "").replace("'", "\\'")
    if by == "label":
        lines.append(f"{prefix}{call}.select.by_text('{value}')")
    elif by == "value":
        lines.append(f"{prefix}{call}.select.by_value('{value}')")
    elif by == "index":
        lines.append(f"{prefix}{call}.select.by_index({value})")


# ── Extraction ────────────────────────────────────────────────────

@_handler("getText")
def _emit_getText(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    var = _var_ref(extra.get("varName", "text"))
    lines.append(f"{prefix}{var} = {call}.text")


@_handler("getAttr")
def _emit_getAttr(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    attr = (extra.get("attrName") or "").replace("'", "\\'")
    var = _var_ref(extra.get("varName", "attrVal"))
    lines.append(f"{prefix}{var} = {call}.attr('{attr}')")


@_handler("getHtml")
def _emit_getHtml(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    mode = extra.get("mode", "inner")
    var = _var_ref(extra.get("varName", "html"))
    if mode == "outer":
        lines.append(f"{prefix}{var} = {call}.html")
    else:
        lines.append(f"{prefix}{var} = {call}.inner_html")


@_handler("getValue")
def _emit_getValue(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    var = _var_ref(extra.get("varName", "value"))
    lines.append(f"{prefix}{var} = {call}.value")


@_handler("getElementCount")
def _emit_getElementCount(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    var = _var_ref(extra.get("varName", "count"))
    lines.append(f"{prefix}{var} = len({call})")


@_handler("getElementList")
def _emit_getElementList(node, extra, depth, prefix, by_parent, lines):
    loc = (node.locator or "").replace("'", "\\'")
    var = _var_ref(extra.get("varName", "elements"))
    lines.append(f"{prefix}{var} = tab.eles('{loc}')")


# ── Scroll ────────────────────────────────────────────────────────

@_handler("scrollToBottom")
def _emit_scrollToBottom(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}tab.scroll.to_bottom()")


@_handler("scrollToTop")
def _emit_scrollToTop(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}tab.scroll.to_top()")


@_handler("scrollIntoView")
def _emit_scrollIntoView(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    block = extra.get("block", "center")
    lines.append(f"{prefix}{call}.scroll.into_view(align='{block}')")


@_handler("scrollBy")
def _emit_scrollBy(node, extra, depth, prefix, by_parent, lines):
    x = extra.get("x", 0)
    y = extra.get("y", 500)
    lines.append(f"{prefix}tab.scroll.by({x}, {y})")


@_handler("infiniteScroll")
def _emit_infiniteScroll(node, extra, depth, prefix, by_parent, lines):
    end_marker = (extra.get("endMarker") or "").replace("'", "\\'")
    max_scrolls = extra.get("maxScrolls", 50)
    interval = extra.get("interval", 2.0)
    click_more = extra.get("clickMoreSelector", "").replace("'", "\\'")

    lines.append(f"{prefix}# Infinite scroll")
    lines.append(f"{prefix}_scroll_count = 0")
    lines.append(f"{prefix}while _scroll_count < {max_scrolls}:")
    lines.append(f"{prefix}    _body_text = tab.ele('body').text")
    if end_marker:
        lines.append(f"{prefix}    if '{end_marker}' in _body_text:")
        lines.append(f"{prefix}        break")
    if click_more:
        lines.append(f"{prefix}    for _more in tab.eles('{click_more}'):")
        lines.append(f"{prefix}        try: _more.click()")
        lines.append(f"{prefix}        except: pass")
    lines.append(f"{prefix}    tab.scroll.by(0, 800)")
    lines.append(f"{prefix}    tab.wait({interval})")
    lines.append(f"{prefix}    _scroll_count += 1")


# ── Wait ──────────────────────────────────────────────────────────

@_handler("sleep")
def _emit_sleep(node, extra, depth, prefix, by_parent, lines):
    sec = extra.get("seconds", 1.0)
    lines.append(f"{prefix}tab.wait({sec})")


@_handler("waitForElement")
def _emit_waitForElement(node, extra, depth, prefix, by_parent, lines):
    loc = (node.locator or "").replace("'", "\\'")
    timeout = extra.get("timeout", 10)
    lines.append(f"{prefix}tab.wait.ele_displayed('{loc}', timeout={timeout})")


@_handler("waitForElementHide")
def _emit_waitForElementHide(node, extra, depth, prefix, by_parent, lines):
    loc = (node.locator or "").replace("'", "\\'")
    timeout = extra.get("timeout", 10)
    lines.append(f"{prefix}tab.wait.ele_hidden('{loc}', timeout={timeout})")


@_handler("waitForText")
def _emit_waitForText(node, extra, depth, prefix, by_parent, lines):
    loc = (node.locator or "").replace("'", "\\'")
    text = (extra.get("text") or "").replace("'", "\\'")
    timeout = extra.get("timeout", 10)
    lines.append(f"{prefix}tab.wait.ele_text('{loc}', '{text}', timeout={timeout})")


@_handler("waitForUrl")
def _emit_waitForUrl(node, extra, depth, prefix, by_parent, lines):
    pattern = (extra.get("urlPattern") or "").replace("'", "\\'")
    timeout = extra.get("timeout", 10)
    lines.append(f"{prefix}tab.wait.url_change('{pattern}', timeout={timeout})")


@_handler("waitForLoad")
def _emit_waitForLoad(node, extra, depth, prefix, by_parent, lines):
    timeout = extra.get("timeout", 30)
    lines.append(f"{prefix}tab.wait.load_start(timeout={timeout})")


# ── Condition (if*) ───────────────────────────────────────────────

@_handler("ifElementExists")
def _emit_ifElementExists(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}if {call}:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifElementNotExists")
def _emit_ifElementNotExists(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}if not {call}:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifElementVisible")
def _emit_ifElementVisible(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    lines.append(f"{prefix}if {call}.states.is_displayed:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifTextContains")
def _emit_ifTextContains(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    text = (extra.get("text") or "").replace("'", "\\'")
    lines.append(f"{prefix}if '{text}' in ({call}.text or ''):")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifTextEquals")
def _emit_ifTextEquals(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    text = (extra.get("text") or "").replace("'", "\\'")
    lines.append(f"{prefix}if ({call}.text or '') == '{text}':")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifUrlContains")
def _emit_ifUrlContains(node, extra, depth, prefix, by_parent, lines):
    pattern = (extra.get("urlPattern") or "").replace("'", "\\'")
    lines.append(f"{prefix}if '{pattern}' in tab.url:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifVarEquals")
def _emit_ifVarEquals(node, extra, depth, prefix, by_parent, lines):
    var = _var_ref(extra.get("varName", "x"))
    value = (extra.get("value") or "").replace("'", "\\'")
    vtype = extra.get("valueType", "string")
    if vtype == "number":
        lines.append(f"{prefix}if {var} == {value}:")
    elif vtype == "bool":
        val = "True" if value.lower() in ("true", "1", "yes") else "False"
        lines.append(f"{prefix}if {var} == {val}:")
    else:
        lines.append(f"{prefix}if {var} == '{value}':")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("ifVarGreaterThan")
def _emit_ifVarGreaterThan(node, extra, depth, prefix, by_parent, lines):
    var = _var_ref(extra.get("varName", "x"))
    value = extra.get("value", 0)
    lines.append(f"{prefix}if {var} > {value}:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("else")
def _emit_else(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}else:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("endIf")
def _emit_endIf(node, extra, depth, prefix, by_parent, lines):
    pass  # Structural marker, no code


# ── Loop ──────────────────────────────────────────────────────────

@_handler("forEachElement")
def _emit_forEachElement(node, extra, depth, prefix, by_parent, lines):
    call = _loc_call(node, extra)
    item_var = _var_ref(extra.get("itemVar", "item"))
    idx_var = _var_ref(extra.get("indexVar", "index"))
    lines.append(f"{prefix}for {idx_var}, {item_var} in enumerate({call}):")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("forRange")
def _emit_forRange(node, extra, depth, prefix, by_parent, lines):
    start = extra.get("start", 0)
    end = extra.get("end", 10)
    step = extra.get("step", 1)
    var = _var_ref(extra.get("varName", "i"))
    lines.append(f"{prefix}for {var} in range({start}, {end}, {step}):")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("forList")
def _emit_forList(node, extra, depth, prefix, by_parent, lines):
    list_var = _var_ref(extra.get("listVar", "items"))
    item_var = _var_ref(extra.get("itemVar", "item"))
    idx_var = _var_ref(extra.get("indexVar", "index"))
    lines.append(f"{prefix}for {idx_var}, {item_var} in enumerate({list_var}):")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("whileCondition")
def _emit_whileCondition(node, extra, depth, prefix, by_parent, lines):
    cond_type = extra.get("conditionType", "elementExists")
    max_iter = extra.get("maxIterations", 100)

    lines.append(f"{prefix}_iter = 0")
    lines.append(f"{prefix}while _iter < {max_iter}:")

    # Condition check at top
    ip = _indent(depth + 1)
    if cond_type == "elementExists":
        loc = (extra.get("locator") or "").replace("'", "\\'")
        lines.append(f"{ip}if not tab.ele('{loc}'):")
        lines.append(f"{ip}    break")
    elif cond_type == "elementNotExists":
        loc = (extra.get("locator") or "").replace("'", "\\'")
        lines.append(f"{ip}if tab.ele('{loc}'):")
        lines.append(f"{ip}    break")
    elif cond_type == "urlContains":
        pattern = (extra.get("urlPattern") or "").replace("'", "\\'")
        lines.append(f"{ip}if '{pattern}' in tab.url:")
        lines.append(f"{ip}    break")
    elif cond_type == "varEquals":
        var = _var_ref(extra.get("varName", "x"))
        val = (extra.get("varValue") or "").replace("'", "\\'")
        lines.append(f"{ip}if {var} == '{val}':")
        lines.append(f"{ip}    break")

    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)

    lines.append(f"{ip}_iter += 1")


@_handler("break")
def _emit_break(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}break")


@_handler("continue")
def _emit_continue(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}continue")


@_handler("endFor")
def _emit_endFor(node, extra, depth, prefix, by_parent, lines):
    pass  # Structural marker


# ── Variables ─────────────────────────────────────────────────────

@_handler("setVar")
def _emit_setVar(node, extra, depth, prefix, by_parent, lines):
    var = _var_ref(extra.get("name", "x"))
    value = extra.get("value", "")
    vtype = extra.get("valueType", "string")
    if vtype == "number":
        lines.append(f"{prefix}{var} = {value}")
    elif vtype == "bool":
        val = "True" if str(value).lower() in ("true", "1", "yes") else "False"
        lines.append(f"{prefix}{var} = {val}")
    elif vtype == "list":
        lines.append(f"{prefix}{var} = []")
    else:
        val = str(value).replace("'", "\\'")
        lines.append(f"{prefix}{var} = '{val}'")


@_handler("appendToList")
def _emit_appendToList(node, extra, depth, prefix, by_parent, lines):
    list_var = _var_ref(extra.get("listName", "items"))
    value = str(extra.get("value", "")).replace("'", "\\'")
    lines.append(f"{prefix}{list_var}.append('{value}')")


@_handler("stringConcat")
def _emit_stringConcat(node, extra, depth, prefix, by_parent, lines):
    target = _var_ref(extra.get("targetVar", "result"))
    parts = [extra.get("part1", ""), extra.get("part2", ""), extra.get("part3", "")]
    parts = [p.replace("'", "\\'") for p in parts if p]
    if parts:
        joined = " + ".join(f"'{p}'" for p in parts)
        lines.append(f"{prefix}{target} = {joined}")
    else:
        lines.append(f"{prefix}{target} = ''")


@_handler("increment")
def _emit_increment(node, extra, depth, prefix, by_parent, lines):
    var = _var_ref(extra.get("varName", "count"))
    step = extra.get("step", 1)
    lines.append(f"{prefix}{var} += {step}")


# ── Output ────────────────────────────────────────────────────────

@_handler("log")
def _emit_log(node, extra, depth, prefix, by_parent, lines):
    msg = (extra.get("message") or "").replace("'", "\\'")
    level = extra.get("level", "info")
    lines.append(f"{prefix}print('[{level.upper()}] {msg}')")


@_handler("pushItem")
def _emit_pushItem(node, extra, depth, prefix, by_parent, lines):
    expr = extra.get("dataExpr", "{}")
    # Try to parse as JSON for pretty printing, fall back to raw
    try:
        parsed = json.loads(expr)
        expr_str = json.dumps(parsed, ensure_ascii=False, indent=None).replace("'", "\\'")
    except Exception:
        expr_str = expr.replace("'", "\\'")
    lines.append(f"{prefix}_results.append({expr_str})")


@_handler("takeScreenshot")
def _emit_takeScreenshot(node, extra, depth, prefix, by_parent, lines):
    path = (extra.get("savePath") or "screenshot.png").replace("'", "\\'")
    full = extra.get("fullPage", False)
    loc = extra.get("locator", "").replace("'", "\\'")
    if loc:
        lines.append(f"{prefix}tab.ele('{loc}').get_screenshot(path='{path}')")
    elif full:
        lines.append(f"{prefix}tab.get_screenshot(path='{path}', full_page=True)")
    else:
        lines.append(f"{prefix}tab.get_screenshot(path='{path}')")


@_handler("saveToFile")
def _emit_saveToFile(node, extra, depth, prefix, by_parent, lines):
    data_var = _var_ref(extra.get("dataVar", "data"))
    path = (extra.get("filePath") or "data.json").replace("'", "\\'")
    fmt = extra.get("format", "json")
    if fmt == "json":
        lines.append(f"{prefix}import json")
        lines.append(f"{prefix}with open('{path}', 'w', encoding='utf-8') as f:")
        lines.append(f"{prefix}    json.dump({data_var}, f, ensure_ascii=False, indent=2)")
    else:
        lines.append(f"{prefix}import csv")
        lines.append(f"{prefix}with open('{path}', 'w', newline='', encoding='utf-8') as f:")
        lines.append(f"{prefix}    writer = csv.DictWriter(f, fieldnames={data_var}[0].keys())")
        lines.append(f"{prefix}    writer.writeheader()")
        lines.append(f"{prefix}    writer.writerows({data_var})")


# ── Mouse/Keyboard ────────────────────────────────────────────────

@_handler("keyCombo")
def _emit_keyCombo(node, extra, depth, prefix, by_parent, lines):
    keys = extra.get("keys", "")
    # Parse simple combos like "Ctrl+A" or "Ctrl+Shift+T"
    parts = [k.strip() for k in keys.split("+") if k.strip()]
    if parts:
        combo = ", ".join(f"Keys.{p}" for p in parts)
        lines.append(f"{prefix}tab.actions.key_down({combo}).key_up({combo})")
    else:
        lines.append(f"{prefix}# keyCombo: {keys}")


# ── Network ───────────────────────────────────────────────────────

@_handler("httpRequest")
def _emit_httpRequest(node, extra, depth, prefix, by_parent, lines):
    method = extra.get("method", "GET")
    url = (extra.get("url") or "").replace("'", "\\'")
    headers_str = extra.get("headers", "")
    body = extra.get("body", "")
    timeout = extra.get("timeout", 30)
    result_var = _var_ref(extra.get("resultVar", "response"))

    lines.append(f"{prefix}import requests")
    lines.append(f"{prefix}{result_var} = requests.{method.lower()}('{url}'")

    if headers_str:
        try:
            headers = json.loads(headers_str)
            lines.append(f"{prefix}    , headers={json.dumps(headers)}")
        except Exception:
            pass

    if body and method in ("POST", "PUT"):
        try:
            json_body = json.loads(body)
            lines.append(f"{prefix}    , json={json_body}")
        except Exception:
            b = body.replace("'", "\\'")
            lines.append(f"{prefix}    , data='{b}'")

    lines.append(f"{prefix}    , timeout={timeout})")


# ── AI ────────────────────────────────────────────────────────────

@_handler("callAiApp")
def _emit_callAiApp(node, extra, depth, prefix, by_parent, lines):
    app_type = extra.get("appType", "")
    inputs = extra.get("inputs", "{}")
    result_var = _var_ref(extra.get("resultVar", "aiResult"))
    lines.append(f"{prefix}# TODO: call AI app '{app_type}' with inputs={inputs}")
    lines.append(f"{prefix}{result_var} = None")


# ── Sub-workflow ──────────────────────────────────────────────────

@_handler("callWorkflow")
def _emit_callWorkflow(node, extra, depth, prefix, by_parent, lines):
    wf_id = extra.get("workflowId", 0)
    inputs = extra.get("inputs", "")
    lines.append(f"{prefix}# TODO: call workflow {wf_id}")


@_handler("return")
def _emit_return(node, extra, depth, prefix, by_parent, lines):
    expr = extra.get("resultExpr", "")
    if expr:
        try:
            parsed = json.loads(expr)
            expr_str = json.dumps(parsed, ensure_ascii=False)
            lines.append(f"{prefix}return {expr_str}")
        except Exception:
            lines.append(f"{prefix}return {expr}")
    else:
        lines.append(f"{prefix}return {{'total': len(_results), 'items': _results}}")


# ── Exception handling ────────────────────────────────────────────

@_handler("try")
def _emit_try(node, extra, depth, prefix, by_parent, lines):
    lines.append(f"{prefix}try:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("catch")
def _emit_catch(node, extra, depth, prefix, by_parent, lines):
    err_var = _var_ref(extra.get("errorVar", "error"))
    lines.append(f"{prefix}except Exception as {err_var}:")
    for child in by_parent.get(node.id, []):
        _emit_dispatch(child, json.loads(child.extra) if child.extra else {}, depth + 1, by_parent, lines)


@_handler("endTry")
def _emit_endTry(node, extra, depth, prefix, by_parent, lines):
    pass  # Structural marker


# ── Custom ────────────────────────────────────────────────────────

@_handler("custom")
def _emit_custom(node, extra, depth, prefix, by_parent, lines):
    code = extra.get("code", "")
    desc = extra.get("description", "")
    if desc:
        lines.append(f"{prefix}# {desc}")
    for line in code.splitlines():
        lines.append(f"{prefix}{line}")


@_handler("executeJs")
def _emit_executeJs(node, extra, depth, prefix, by_parent, lines):
    script = extra.get("script", "").replace("'", "\\'")
    result_var = _var_ref(extra.get("resultVar", "jsResult"))
    lines.append(f"{prefix}{result_var} = tab.run_js('''{script}''')")
