"""
Workflow → DrissionPage Python script exporter.

Each command type has its own emit_* function for clean separation.
Emit handlers live in emitters/ and are auto-discovered on import.
"""

import json
from typing import Any

from src.repo import runtime_models as models

# Trigger emitter registration
import src.runtime.workflow.emitters  # noqa: F401
from src.runtime.workflow.emitters._registry import _emit_dispatch


def build_python(wf: models.Workflow, flat_nodes: list[models.WorkflowNode], repo_root: str = "") -> list[str]:
    """Generate DrissionPage Python lines from a workflow and its nodes."""
    print(f"[exporter] building python for '{wf.name}' with {len(flat_nodes)} nodes")
    lines = [
        "# AUTO-GENERATED by workflow exporter",
        "# DO NOT EDIT — changes will be overwritten",
        "",
        "import sys, os",
        f"_repo = os.environ.get('RPA_REPO_ROOT', {repr(repo_root)})",
        "_project_root = os.path.dirname(_repo)",
        "if _project_root and _project_root not in sys.path:",
        "    sys.path.insert(0, _project_root)",
        "",
        "from src.repo.chrome_utils import connect_chrome",
        "",
        "# Workflow error handler — maps traceback back to workflow node",
        "import traceback, re",
        "",
        "def _wf_excepthook(exc_type, exc_value, tb):",
        "    node_info = None",
        "    t = tb",
        "    while t:",
        "        co = t.tb_frame.f_code",
        "        if co.co_filename == __file__:",
        "            lineno = t.tb_lineno",
        "            try:",
        "                with open(__file__, 'r', encoding='utf-8') as f:",
        "                    src = f.readlines()",
        "                for i in range(lineno - 1, -1, -1):",
        "                    m = re.search(r'# WF_NODE id=(\\d+) type=(\\S+) label=(.+)', src[i])",
        "                    if m:",
        "                        node_info = {'id': int(m.group(1)), 'type': m.group(2), 'label': m.group(3).strip()}",
        "                        break",
        "            except Exception:",
        "                pass",
        "            if node_info:",
        "                break",
        "        t = tb.tb_next",
        "    if node_info:",
        "        print(f\"[WF_ERROR] 指令 #{node_info['id']} ({node_info['type']}) {node_info['label']}\", file=sys.stderr)",
        "    traceback.print_exception(exc_type, exc_value, tb)",
        "",
        "sys.excepthook = _wf_excepthook",
        "",
        f"# Workflow: {wf.name}",
        f"# URL: {wf.url or 'TODO'}",
        "",
        "tab = connect_chrome()",
        "if not tab:",
        "    raise RuntimeError('无法连接到 Chrome，请确保 Chrome 已启动并开启了远程调试端口 9222')",
    ]
    if wf.url:
        lines.append(f"tab.get('{wf.url}')")
    lines.append("")

    # Build parent→children map
    by_parent: dict[int | None, list[models.WorkflowNode]] = {}
    for n in flat_nodes:
        pid = n.parent_id
        by_parent.setdefault(pid, []).append(n)
    for children in by_parent.values():
        children.sort(key=lambda n: n.order)

    # Collect results container
    lines.append("_results = []")
    lines.append("")

    def _emit(node: models.WorkflowNode, depth: int = 0) -> None:
        extra = json.loads(node.extra) if node.extra else {}
        _emit_dispatch(node, extra, depth, by_parent, lines)

    # Emit root nodes
    for n in by_parent.get(None, []):
        _emit(n, 0)

    lines.append("")
    lines.append("print('Workflow completed')")
    lines.append(f"print(f'Results: {{len(_results)}} items')")
    return lines
