"""
Build background.js by concatenating base infrastructure + background handler files.
Output to dist/desktop/extension/ only. Chrome loads extension from this directory.
"""
import os, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_FILE = os.path.join(ROOT, "extension", "background_base.js")
HANDLERS_DIR = os.path.join(ROOT, "extension", "background_handlers")
OUTPUT_PATHS = [
    os.path.join(ROOT, "dist", "desktop", "extension", "background.js"),
]

def main():
    with open(BASE_FILE, encoding="utf-8") as f:
        content = f.read()

    # Load background handlers (*.js only, skip _load_all.js and _ prefixed)
    handler_files = sorted(
        fp for fp in glob.glob(os.path.join(HANDLERS_DIR, "*.js"))
        if not os.path.basename(fp).startswith("_")
    )
    handler_code = ""
    for fp in handler_files:
        name = os.path.splitext(os.path.basename(fp))[0]
        with open(fp, encoding="utf-8") as f:
            handler_code += f"\n// ── {name} ──\n"
            handler_code += f.read() + "\n"

    # Insert handlers at the marker
    marker = "// ─── Background handlers (generated by build_background_js.py) ───"
    if marker in content:
        content = content.replace(marker, marker + "\n" + handler_code)
    else:
        content += "\n" + handler_code

    for out_path in OUTPUT_PATHS:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Wrote {out_path} ({len(content)} bytes)")

if __name__ == "__main__":
    main()
